[package]
name = "declavalidate"
version = "0.25.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
declavatar = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
static_vcruntime = { workspace = true }
