[package]
name = "avatar-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
declavatar = { path = "../declavatar" }
miette = { version = "5.5.0", features = ["fancy"]}
