[package]
name = "declavatar"
version = "0.3.0"
edition = "2021"

[features]
cdylib = []

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
kdl = "4.6.0"
miette = "5.5.0"
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"

[build-dependencies]
static_vcruntime = { version = "2.0.0" }
