[package]
name = "declavatar"
version = "0.3.0"
edition = "2021"

[features]
cdylib = []

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
kdl = "4.6.0"
miette = "5.7.0"
semver = "1.0.17"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.95"
thiserror = "1.0.40"

[build-dependencies]
static_vcruntime = { version = "2.0.0" }
