[package]
name = "declavatar"
version = "0.9.0"
edition = "2021"

[features]
cdylib = []

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
kdl = "4.6.0"
ketos = { version = "0.12.0", features = ["derive"] }
miette = "5.10.0"
semver = "1.0.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"

[build-dependencies]
static_vcruntime = { version = "2.0.0" }
