name: "Build library on x86_64 Mac"

on:
  workflow_dispatch:

jobs:
  build-x86_64-apple-darwin:
    name: "Build"
    runs-on: "macos-latest"

    steps:
      - uses: "actions/checkout@v3"
      - shell: "bash"
        run: |
          mkdir '.cargo'
          echo '[registries.crates-io]' >> .cargo/config.toml
          echo 'protocol = "sparse"' >> .cargo/config.toml

      - uses: "actions-rust-lang/setup-rust-toolchain@v1"
      - shell: "bash"
        run: |
          cargo build --all-features --release

      - uses: "actions/upload-artifact@v3"
        with:
          name: "built library"
          path: "./target/release/libdeclavatar.dylib"
