name: "Check Rust Codes"

on:
  - "push"
  - "pull_request"

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions-rust-lang/setup-rust-toolchain@v1"
        with:
          components: "rustfmt, clippy"
      - shell: "bash"
        run: |
          mkdir '.cargo'
          echo '[registries.crates-io]' >> .cargo/config.toml
          echo 'protocol = "sparse"' >> .cargo/config.toml

      - uses: "actions-rust-lang/rustfmt@v1"
      - shell: "bash"
        run: |
          cargo clippy --all-features

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions-rust-lang/setup-rust-toolchain@v1"
        with:
          components: "rustfmt, clippy"
      - shell: "bash"
        run: |
          mkdir '.cargo'
          echo '[registries.crates-io]' >> .cargo/config.toml
          echo 'protocol = "sparse"' >> .cargo/config.toml

      - shell: "bash"
        run: |
          cargo test --all-features
